################################# Network ######################################
bind 0.0.0.0
# protected-mode yes

################################# Logging ######################################
logfile ""
loglevel notice

################################# Persistence ##################################
dir /data
save 900 1
appendonly yes
appendfsync everysec

################################# Threads ######################################
io-threads 2

################################# Security #####################################
# DO NOT put requirepass here if you inject it via CLI args
# requirepass ${REDIS_PASSWORD}   <- delete/comment out
