version: '3.1'

services:
    nyks:
        container_name: "nyks"
        build:
          context: ./
          dockerfile: ./nyks/Dockerfile
        ports:
            - "1317:1317"
            - "26656:26656"
            - "26657:26657"
            - "26660:26660"
        expose:
            - "1317"
            - "26656"
            - "26657"
            - "26660"
        volumes:
            - ./nyks/data:/root/.nyks
        # command : ["./wait_for_it.sh", "postgres:5432", "--", "./nyks_entrypoint.sh"]
        command: ["./nyks_entrypoint.sh"]
        networks:
            - network_conn
        
networks:
  network_conn: