FROM rust:1.87.0 as builder
RUN USER=root apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install git curl g++ build-essential libssl-dev pkg-config && \
    apt-get -y install software-properties-common && \
    apt-get update 

RUN git clone -b develop-fee https://github.com/twilight-project/relayer-data-api.git
WORKDIR /relayer-data-api
RUN cargo build --release --bins    

FROM rust
RUN apt-get update && apt-get install -y ca-certificates curl libpq-dev libssl-dev
EXPOSE 5000
EXPOSE 8989
EXPOSE 8990
EXPOSE 8987

WORKDIR /app

ARG BINARY
COPY --from=builder ./relayer-data-api/target/release/${BINARY} ./main
COPY --from=builder ./relayer-data-api/target/release/${BINARY}.d ./main.d
ENTRYPOINT ["/app/main"]